prose:
  rooturl: ''
  siteurl: 'http://scotentSD.github.io/opportunity/'
  relativeLinks: 'http://scotentSD.github.io/opportunity/links.jsonp'
  media: 'files'
  metadata:
   _posts:
    - name: "layout"
      field:
        element: "hidden"
        value: "post"
    - name: "type"
      field:
        element: "select"
        label: "Type"
        placeholder: ""
        options:
          - name: " lab "
            value: "lab"
          - name: " online "
            value: "online"
          - name: " a11y "
            value: "a11y"
          - name: " other "
            value: "other"
          - name: " partner"
            value: "partner"
    - name: "phase"
      field:
        element: "select"
        label: "Phase"
        placeholder: ""
        options:
         - name: "discovery"
           value: "discovery"
         - name: "alpha"
           value: "alpha"
         - name: "beta"
           value: "beta"
         - name: "live"
           value: "live"
    - name: "initials"
      field:
        element: "text"
        label: "Initials"
        value: ""
    - name: "display_date"
      field:
        element: "text"
        label: "Display_Date"
        value: ""
    - name: "tltitle"
      field:
        element: "text"
        label: "Title"
        value: ""
    - name: "return_url"
      field:
        element: "hidden"
        value: "https://scotentsd.github.io/sep/timeline/"

 


theme: jekyll-theme-slate
title: Opportunity Management
description:  
excerpt_separator: "<!--more-->"
baseurl: "/opportunity/"
permalink: /:title/
# The release of Jekyll Now that you're using
version: v1.2.0
plugins:
  - jekyll-relative-links
  
 
collections:
  flist:
    output: true



  
