theme: jekyll-theme-slate
title: Opportunity Management
description:  
excerpt_separator: "<!--more-->"
baseurl: "/customer-account/"
permalink: /:title/
# The release of Jekyll Now that you're using
version: v1.2.0
plugins:
  - jekyll-relative-links
